routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'IndexController@index')->name('home');
Route::get('/documents', 'IndexController@documents')->name('documents');
Route::get('/documents/policy', 'IndexController@policy')->name('policy');
Route::get('/documents/cookie', 'IndexController@cookie')->name('cookie');
Route::get('/documents/rules', 'IndexController@rules')->name('rules');
Route::get('/posts', 'PostController@index')->name('news');
Route::get('/post/{id}-{path}', 'PostController@expand')->name('post');

Route::post('/donate/notification', 'PaymentController@receiveNotification');

//Route::get('/donate/test', 'PaymentController@test');

Route::get('/dd6e027ad9fbf25e2285b7c422b8656b.html', function () {
})->name('lolkek');

Route::prefix('validation')->group(function () {
    Route::get('registration', 'ValidationController@handle')->name('validate-registration');
});

Route::get('/registration', 'UserController@create');
Route::post('/user/login', 'Auth\LoginController@login');
Route::resource('user', 'UserController')->only([
    'store'
]);

Route::get('/vkontakte/game', 'GameController@createGameViaVkontakte')->middleware('character')->name('game');

Route::middleware('auth')->group(function () {
    Route::get('/settings', 'SettingsController@show')->name('settings');
    Route::post('/settings', 'SettingsController@save')->name('settings-save');

    Route::get('/donate', 'PaymentController@show')->name('donate');
    Route::post('/donate', 'PaymentController@redirectToPay');
    Route::post('/donate/transit', 'PaymentController@transitToGame')->name('transit');

    Route::get('/character/create', 'CharactersController@show')->name('create-character');
    Route::post('/character/create', 'CharactersController@create');


    Route::get('/registration-completing', 'Auth\RegisterController@showRegistrationCompleteForm')->name('registration-complete');
    Route::post('/registration-completing', 'Auth\RegisterController@completingRegistration')->name('registration-completing');

    Route::group(['middleware' => ['level:10']], function () {
        Route::prefix('admin')->group(function () {
            Route::get('/slides/create', 'AdminController@showSlideCreate')->middleware('permission:slide.add')->name('slide.create');
            Route::post('/slides/create', 'SliderController@create')->middleware('permission:slide.add');
            Route::get('/posts/create', 'AdminController@showPostCreate')->middleware('permission:post.add')->name('admin.post-create');
            Route::post('/posts/create', 'PostController@create')->middleware('permission:post.add');
        });
    });

    Route::group(['middleware' => ['level:10']], function () {
        Route::prefix('telegram-bot')->group(function () {
            Route::get('/activate', 'AdminController@activateTelegramBot')->middleware('permission:telegram.activate')->name('admin.telegram.activate');
        });
    });

});

Route::any('1094810348:AAE7Xu6rE7nHPM7KHAyh96xna892CK6vGz8/webhook', 'TelegramController@handle');



Route::get('events', 'EventController@view')->name('events');

Route::prefix('2fa')->group(function () {
    Route::get('enable', 'Google2FAController@enableTwoFactor')->middleware('auth');
    Route::post('enable', 'Google2FAController@confirmTwoFactor')->middleware('auth')->name('confirmTwoFactor');
    Route::get('disable', 'Google2FAController@disablePageTwoFactor')->middleware('auth');
    Route::post('disable', 'Google2FAController@disableTwoFactor')->middleware('auth')->name('disableTwoFactor');
    Route::get('validate', 'Auth\LoginController@getValidateToken')->name('LoginVia2fa');
    Route::post('validate', ['middleware' => 'throttle:5', 'uses' => 'Auth\LoginController@postValidateToken']);
});



Route::prefix('social')->group(function () {
    Route::get('{driver}/redirect', 'SocialController@redirect')->name('social-auth');
    Route::get('{driver}/callback', 'SocialController@callback');
});

Route::prefix('user-old')->group(function () {
    Route::post('login', 'Auth\LoginController@login');
    Route::get('logout', 'Auth\LoginController@logout')->name('logout');

    Route::post('register', 'Auth\RegisterController@register')->name('registration');

    Route::get('email/verify/{id}', 'Auth\VerificationController@verify')->name('verification.verify');
    Route::get('email/resend', 'Auth\VerificationController@resend')->name('verification.resend');

    Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');
});

resources/views/documents.blade.php
@extends('layouts.app')

@push('async-scripts')

@endpush

@push('async-css')
    <link rel="stylesheet" href="{{ mix('/css/documents.css') }}">
@endpush

@section('content')
    <div class="block documents">
        <h2 class="h2">Документы</h2>
        <div>
            <p>Здесь собранны все необходимые документы к прочтению :)</p>
            <ol>
                <li><a class="link" href="{{ route('policy') }}">Политика в отношении обработки персональных данных</a></li>
                <li><a class="link" href="{{ route('rules') }}">Правила сервера</a></li>
                <li><a class="link" href="{{ route('cookie') }}">Cookie Policy</a></li>
            </ol>
        </div>
    </div>
@endsection

resources/views/game.blade.php
<html lang="ru_RU">
    <head>

        <title></title>
        <style>
            .background {
                background-image: url('{{ url("img/bg-all.jpg") }}');
                background-position: center;
                background-repeat: no-repeat;
                box-shadow: 0 0 32px 32px #311c47 inset;
                width: 1920px;
                height: 1200px;
                z-index: -1;
                position: absolute;
                top: 50%;
                left: 50%;
                transform: translate(-50%, -50%);
            }
            body {
                background-color: #311c47;
                margin:0;
                padding:0;
                overflow: hidden;
            }
        </style>
		<script>
		function toLocation(patch, msg)
		{
			alert(msg);
		}
		</script>
    </head>
    <body>
        <div class="background"></div>
        <div style="display: flex;
                    align-items: center;
                    justify-content: center;
                    height: 100%;
                    min-width: 1000px;
                    min-height: 600px;
                    ">
            <div style="">
                <object id="7road-ddt-game" name="Main" width="1000" height="600" align="middle">
                    <param name="allowScriptAccess" value="always">
                    <param name="movie" value="{{ config('game.flash') }}/preloader.swf?user={{ $name }}&flashURL={{ urlencode(config('game.flash')) }}&key={{ $pass }}&config={{ $config }}">
                    <param name="quality" value="high">
                    <param name="menu" value="false">
                    <param name="bgcolor" value="#000000">
                    <param name="FlashVars" value="site=bb.mail.ru&sitename=&rid=&enterCode=">
                    <param name="allowScriptAccess" value="always">
                    <param name="wmode" value="direct">
                    <embed flashvars="site=bb.mail.ru&sitename=&rid=&enterCode=" src="{{ config('game.flash') }}/preloader.swf?user={{ $name }}&flashURL={{ urlencode(config('game.flash')) }}&key={{ $pass }}&config={{ $config }}" width="1000" height="600" align="middle" quality="high" name="Main" allowscriptaccess="always" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" wmode="direct">
                </object>
            </div>
        </div>
    </body>
</html>

resources/views/index.blade.php
@extends('layouts.app')

@section('slider')
    <div id="slider" class="block slider" data-dynamic="true" data-api="{{ config('plugins.slider_api') }}">
        <div class="viewport">
            <ul class="slide-wrapper">

            </ul>

            <div class="prev"></div>
            <div class="next"></div>

            <ul class="navigation-buttons">
            </ul>

        </div>
    </div>
@endsection

@push('async-scripts')
    async('{{ mix('/js/slider.js') }}', function() {
        $('#slider').slider();
    });
@endpush

@push('async-css')
    <link rel="stylesheet" href="{{ mix('/css/news.css') }}">
@endpush
@push('css')
    <link rel="stylesheet" href="{{ mix('/css/modules/slider.css') }}">
@endpush

@section('content')
    @Posts(['isPaginate' => false, 'posts' => $posts])
    @endPosts
@endsection

resources/views/payment.blade.php
@extends('layouts.app')

@push('async-css')
    <link rel="stylesheet" href="{{ mix('/css/payment.css') }}">
@endpush

@section('content')
    <div class="block information">
        <h2>Памятка к пополнению и переводу</h2>
        <p class="notice">
            <span>Необходимо выйти из игры перед тем как переводить деньги! Курс перевода <b>ОП</b> в <b>аметисты</b> составляет <b>1</b> к <b>40</b>.
                 Если по какой-то причине аметисты или ОП не пришли на счет, то <span class="no">необходимо</span> обратиться в
                <a href="https://vk.com/im?media=&sel=-187884224"><b><em>тех. поддержку</em></b></a> <sup>(мб даже ответят)</sup>
             </span>
        </p>
    </div>
    <div class="block payment half-of">
        <h2>Пополнение счета</h2>
        <p class="notice">
            <img class="inline" width="36" height="26" src="https://tbank.mail.ru/resources/iframe/images/connection_ico.png" alt="">
            <span class="inline">
                <span class="head" style="font-size: 13px; font-weight: bold;">Безопасное соединение</span>
                <span class="body" style="font-size: 10px;">Передаваемые данные зашифрованы 256-битным ключом</span>
            </span>
        </p>
        <form id="payment" action="{{route('donate')}}" method="POST">
            @csrf
            <label>
                <input class="amount" type="number" step="0.01" name="sum" value="100.00" required>
            </label>
            <input class="submit" type="submit" value="Перейти к пополнению">
        </form>
    </div><!--
    --><div class="block transit half-of">
        <h2>Перевод в игру</h2>
        <p class="notice">
            <img class="inline" width="36" height="26" src="{{ url('/img/attention_ico.png') }}" alt="">
            <span class="inline">
                <span class="head" style="font-size: 13px; font-weight: bold;">Внимание!</span>
                <span class="body" style="font-size: 10px;">Каждые 2000 аметистов = 1 попытка алмазного колеса</span>
            </span>
        </p>
        <form id="transit" action="{{route('transit')}}" method="POST">
            @csrf
            <label>
                <input id="amount" class="amount" type="number" step="0.01" name="sum" value="100.00" required>
            </label>
            <input id="transitToGame" class="submit" type="submit" value="Перевести в игру">
        </form>
    </div>
    <div class="block screenshots">
        <div class="gallery">
            <img src="{{ url('img/screenshots/shop01.png') }}" alt="arm shop">
        </div>
    </div>
@endsection

@push("async-scripts")
    $("#amount").attr({
        "max" : $("#balance").text(),        // substitute your own
    });
    $("#amount").keyup(function() {
        if(Math.round($('#amount').val() * 100) / 100 > Math.round($("#balance").text() * 100) / 100)
        {
            $('#amount').val(Math.round($("#balance").text() * 100) / 100);
        }
        let amount = Math.round($('#amount').val() * 40);
        $('#transitToGame').val("Перевести в игру " + amount + " аметистов")
    });
    $("#amount").keyup();
@endpush

resources/views/registration-completing.blade.php
@extends('layouts.app')

@section('title', 'Завершение регистрации')

@push('async-css')
    <link rel="stylesheet" href="{{ mix('/css/registration.css') }}">
@endpush

@push('async-scripts')
    async('{{ mix('/js/validator.js') }}', function() {
        $('#registration').validator();
    });
@endpush

@section('content')
    <div class="block registration">
        <h2>Завершение регистрации</h2>
        <form id="registration" action="{{ route('registration-completing') }}" method="POST">
            @csrf
            @if(is_null(Auth::user()->email))
            <div class="row">
                <div class="form-group has-feedback">
                    <input data-remote="/validation/registration" data-pattern-error="Email адрес не соотвуствует правилам" data-error="Данный email адрес уже занят" data-required-error="Введите действующий адрес электронной почты" type="email" name="email" placeholder="E-mail" required>
                    <div class="tip">
                        <p class="outer">
                            <span class="inner help-block with-errors">
                                <span class="empty">Введите действующий адрес электронной почты</span>
                                <span class="success">Email адрес свободен и вы можете использовать его!</span>
                            </span>
                        </p>
                    </div>
                </div>
            </div>
            @endif
            @if(is_null(Auth::user()->password))
            <div class="row">
                <div class="form-group has-feedback">
                    <input type="password" name="password" placeholder="Пароль" id="pwd" pattern="(?=^.{8,}$)((?=.*\d)|(?=.*\W+))(?![.\n])(?=.*[A-Z])(?=.*[a-z]).*$" required>
                    <div class="tip">
                        <p class="outer">
                            <span class="inner help-block with-errors">
                                <span class="empty">Придумайте пароль</span>
                                <span class="success">Пароль идеально подходит :)</span>
                            </span>
                        </p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="form-group has-feedback">
                    <input data-match="#pwd" type="password" name="password_confirmation" placeholder="Повторите пароль" required>
                    <div class="tip">
                        <p class="outer">
                            <span class="inner help-block with-errors">
                                <span class="empty">Введите еще раз придуманный пароль</span>
                                <span class="success">Все верно!</span>
                            </span>
                        </p>
                    </div>
                </div>
            </div>
            @endif
            <div class="row">
                <hr>
            </div>
            <div class="row">
                <div class="form-group">
                    <p class="user-agreement">Зарегистрировавшись, вы автоматически принимаете
                        <a href="#" target="_blank">пользовательское соглашение</a>
                        и <a href="#">политику конфиденциальности</a> нашего сервиса.</p>
                    <input class="registration-button" type="submit" value="Завершить регистрацию">
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/registration.blade.php
@extends('layouts.app')

@section('title', 'Регистрация')

@push('async-css')
    <link rel="stylesheet" href="{{ mix('/css/registration.css') }}">
@endpush

@push('async-scripts')
    async('{{ mix('/js/validator.js') }}', function() {
        $('#registration').validator();
    });
@endpush

@section('content')
    <div class="block registration">
        <h2>Регистрация</h2>
        <p class="notice">
            Для регистрации нужно указать действующий адрес электронной почты. Он будет использоваться для
            восстановления данных аккаунта и общения с администрацией игры. Изменить его позднее вы сможете только
            через службу поддержки. Если у вас нет почты, зарегистрируйте ее на любом почтовом сервисе,
            например Gmail / Yandex / Mail.ru.
        </p>
        <form id="registration" action="{{ route('user.store') }}" method="POST">
            @csrf
            {!!  GoogleReCaptchaV3::renderField('regcaption','registration') !!}
            <div class="row">
                <div class="form-group has-feedback">
                    <input data-remote="/validation/registration" data-pattern-error="Логин может содержать только латинские буквы и цифры" data-error="Этот логин уже занят" data-required-error="Введите желаемый логин" type="text" name="username" placeholder="Логин" pattern="^[a-zA-Z][a-zA-Z0-9-_\.]{1,20}$" required>
                    <div class="tip">
                        <p class="outer">
                            <span class="inner help-block with-errors">
                                <span class="empty">Введите желаемый логин</span>
                                <span class="success">Все верно</span>
                            </span>
                        </p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="form-group has-feedback">
                    <input data-remote="/validation/registration" data-pattern-error="Email адрес не соотвуствует правилам" data-error="Данный email адрес уже занят" data-required-error="Введите действующий адрес электронной почты" type="email" name="email" placeholder="E-mail" required>
                    <div class="tip">
                        <p class="outer">
                            <span class="inner help-block with-errors">
                                <span class="empty">Введите действующий адрес электронной почты</span>
                                <span class="success">Все верно</span>
                            </span>
                        </p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="form-group has-feedback">
                    <input type="password" name="password" placeholder="Пароль" id="pwd" pattern="(?=^.{8,}$)((?=.*\d)|(?=.*\W+))(?![.\n])(?=.*[A-Z])(?=.*[a-z]).*$" required>
                    <div class="tip">
                        <p class="outer">
                            <span class="inner help-block with-errors">
                                <span class="empty">Придумайте пароль</span>
                                <span class="success">Все верно</span>
                            </span>
                        </p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="form-group has-feedback">
                    <input data-match="#pwd" type="password" name="password_confirmation" placeholder="Повторите пароль" required>
                    <div class="tip">
                        <p class="outer">
                            <span class="inner help-block with-errors">
                                <span class="empty">Введите еще раз придуманный пароль</span>
                                <span class="success">Все верно</span>
                            </span>
                        </p>
                    </div>
                </div>
            </div>
            <div class="row">
                <hr>
            </div>
            <div class="row">
                <div class="form-group">
                    <p class="user-agreement">Зарегистрировавшись, вы автоматически принимаете
                        <a href="{{ route('rules') }}" target="_blank">пользовательское соглашение</a>
                        и <a href="{{ route('policy') }}">политику конфиденциальности</a> нашего сервиса.</p>
                    <input class="registration-button" type="submit" value="Зарегистрироваться">
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/settings.blade.php
@extends('layouts.app')

@section('title', 'Настройки')

@push('async-css')
    <link rel="stylesheet" href="{{ mix('/css/settings.css') }}">
@endpush

@push('async-scripts')
    async('{{ mix('/js/validator.js') }}', function() {
        $('#account_settings').validator();
    });
@endpush

@section('content')
    <div class="block settings">
        <div>
            <h2>Настройки аккаунта</h2>
            <form id="account_settings" action="{{ route('settings-save') }}" method="post">
                @csrf
                <div class="row">
                    <div class="column full">
                        <div class="form-group">
                            <label for="s_pwd">Текущий пароль *</label>
                            <input id="s_pwd" name="old_password" type="password" required>
                            <div class="help-block with-errors"></div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="column full">
                        <div class="form-group has-feedback">
                            <label for="s_new_pwd">Введите новый пароль</label>
                            <input id="s_new_pwd" name="password" type="password" data-pattern-error="Пароль должен содержать буквы верхнего и нижнего регистра, а так же цифры."  pattern="(?=^.{8,}$)((?=.*\d)|(?=.*\W+))(?![.\n])(?=.*[A-Z])(?=.*[a-z]).*$">
                            <div class="tip-message-body">
                                <div class="outer tip-message">
                                    <div class="inner help-block with-errors">
                                        <span class="empty">Введите новый пароль, если вы хотите изменить его.</span>
                                        <span class="success">После смены пароля на ваш e-mail будет высланно уведомление</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group has-feedback">
                            <label for="s_new_pwd_confirmation">Повторите новый пароль</label>
                            <input id="s_new_pwd_confirmation" name="password_confirmation" type="password" data-match="#s_new_pwd" data-match-error="Ваш новый пароль и подтверждение пароля не совпадают.">
                            <div class="tip-message-body">
                                <div class="outer tip-message">
                                    <div class="inner help-block with-errors">
                                        <span class="empty">Подвердите новый пароль, если вы собираетесь изменить его.</span>
                                        <span class="success">После смены пароля на ваш e-mail будет высланно уведомление</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group has-feedback">
                            <label for="s_email">Текущий E-mail</label>
                            <input id="s_email" name="email" type="email" disabled value="{{ Auth::user()->email ?? "не задан" }}">
                            <div class="tip-message-body">
                                <div class="outer tip-message">
                                    <div class="inner help-block with-errors">
                                        <span class="empty">Это ваш текущий E-mail адресс</span>
                                        <span class="success">Это ваш текущий E-mail адресс</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group has-feedback">
                            <label for="s_new_email">Введите новый E-mail</label>
                            <input id="s_new_email" name="email" type="email">
                            <div class="tip-message-body">
                                <div class="outer tip-message">
                                    <div class="inner help-block with-errors">
                                        <span class="empty">Введи новый email адресс. На него будет выслано письмо с подверждением</span>
                                        <span class="success">Вам необходимо будет подтверить новый адрес с обеих почт.</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <hr>
                </div>
                <div class="row">
                    <div class="form-group">
                        <input class="save-button" type="submit" value="сохранить изменения">
                    </div>
                </div>
                <div class="row">
                    <div class="form-group">
                        <p>
                            * Обязательное поле. Если вы забыли пароль, то, пожалуйста, обратитесь в <a href="#">службу поддержки</a> нашего сервиса.
                        </p>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection